baseURL = "https://higebobo.github.io/hugo-novela"
languageCode = "ja"
title = "Hugo Novela"
theme = "hugo-theme-novela"
paginate = 4

[sosial]
  #twiteer = "#"
  github = "#"
  gitlab = "#"
  bitbucket = "#"
  #instagram = "#"
  #linkedin = "#"
  #dribbble = "#"
  #youtube = "#"

[taxonomies]
  author = "authors"
  #tag = "tags"
  #category = "categories"
  #archive = "archives"

[params]
  baseURL = "https://higebobo.github.io/hugo-novela"
