baseURL = "https://higebobo.github.io/hugo-novela"
languageCode = "ja"
title = "Hugo Novela"
theme = "hugo-theme-novela"

[sosial]
  #twiteer = "#"
  github = "#"
  gitlab = "#"
  bitbucket = "#"
  #instagram = "#"
  #linkedin = "#"
  #dribbble = "#"
  #youtube = "#"

[taxonomies]
  author = "authors"

[params]
  baseURL = "https://higebobo.github.io/hugo-novela"
